services:
  patchpeek:
    build: .
    container_name: patchpeek
    ports:
      - "3321:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    # Uncomment the next line to run container as non-root user (node)
    # user: "1000:1000"
